# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Guilherme Kenzo's Personal Blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: Guilherme Kenzo's Blog
author:
  name: Guilherme Kenzo
  email: guilhermekenzo.s [at] gmail.com
  github: https://github.com/guilherme-kenzo
  twitter: https://twitter.com/Guilherme_kenzo
  pinterest:
  linkedin: https://www.linkedin.com/in/guilherme-kenzo-dos-santos/
  bio: Masters Student at University of São Paulo. Researcher at FGV Law School.
  email_md5:

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
