baseURL: 'https://guilherme-kenzo.github.io/'
languageCode: pt
title: Guilherme Kenzo dos Santos
theme: "PaperMod"
paginate: 2
Copyright: © Guilherme Kenzo dos Santos
canonifyurls: true
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


params:
  description: Guilherme Kenzo's Personal Blog
  authorlocation: São Paulo  
  en:
    LanguageName: "English"
    weight: 2
    menu:
      main:
        - name: Home
          weight: 0
          identifier: home
          pre: <br />
          url: /
        - name: Contact
          weight: 100
          identifier: contact
          pre: <br />
          url: contact/
        - name: Search
          url: search/
          weight: 200

  githubName: guilherme_kenzo
  linkedinName: guilherme-kenzo
  email: guilhermekenzo.s@gmail.com
  hideHUGOSupport: false
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowToc: true
  images: ["papermod-cover.png"]


languages:

  pt:
    LanguageName: "Português"
    weight: 1
    menu:
      main:
        - name: Página Inicial
          weight: 0
          identifier: home
          pre: <br />
          url: /
        - name: Contato
          weight: 100
          identifier: contact
          pre: <br />
          url: contact/
        - name: Busca
          pre: <br />
          url: search/
          weight: 200

  en:
    LanguageName: "English"
    weight: 2
    menu:
      main:
        - name: Home
          weight: 0
          identifier: home
          pre: <br />
          url: /
        - name: Contact
          weight: 100
          identifier: contact
          pre: <br />
          url: contact/
        - name: Search
          url: search/
          weight: 200

sitemap:
  ChangeFreq: ''
  Filename: sitemap.xml
  Priority: '-1'
